# Change these first
owner: jimc66
repo: upptime-email-cheat-code

sites:
  - name: Email Cheat Code
    url: https://emailcheatcode.com

status-website:
  cname: status.emailcheatcode.com
  name: Email Cheat Code Status
  introTitle: "**Email Cheat Code** uptime monitor"
  introMessage: Current status and uptime history for Email Cheat Code
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Upptime workflow schedule (optional, defaults below)
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
